# Generated by Django 3.1.3 on 2020-12-30 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20201230_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
